model:
  base_learning_rate: 1.e-4
  train_target: ldm.models.downstream.segmentation.Segmentator
  test_target: inference.models.InferSegmentator

  params:
    num_classes: 7
    image_key: image
    seg_key: label
    backbone_name: swinunetr
    crop_input: true
    monitor: val.dc.mean_epoch
    image_size: [128, 128, 128]

  test_only_params:
    ckpt_path: $path
    save_dataset: true 
    save_dataset_path: $path
    suffix_keys: 
      mask: .nii.gz

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 16
    wrap: False
    train:
      target: ldm.data.base.MSDDataset
      params:
        split: train
        # max_size: 2
        output_size: [256, 256, 256]
        base_dir: 
          - /home/dlr/data/datasets/msd_hepaticvessel
        transforms:
          torchio.RescaleIntensity:
            in_min_max: [-100, 100]
            out_min_max: [-1, 1]
          torchio.RemapLabels:
            remapping: 
              2: 0
    validation:
      target: ldm.data.base.MSDDataset
      params:
        split: val
        max_size: 10
        output_size: [256, 256, 256]
        base_dir: 
          - /home/dlr/data/datasets/msd_hepaticvessel
        transforms:
          torchio.RescaleIntensity:
            in_min_max: [-100, 100]
            out_min_max: [-1, 1]
          torchio.RemapLabels:
            remapping: 
              2: 0

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: true
    max_epochs: 1000
    replace_sampler_ddp: false
    limit_test_batches: 500
    num_sanity_val_steps: 0