model:
  base_learning_rate: 2e-5
  train_target: ldm.models.cdpm.CategoricalDiffusion
  test_target: inference.models.InferCategoricalDiffusion
  params:
    # diffusion kwargs
    linear_start: 1e-2
    linear_end: 0.2
    log_every_t: 200
    timesteps: 1000
    num_classes: 20  # include background class
    mask_key: label
    noise_type: categorical
    conditioning_key: crossattn
    monitor: val/loss
    cond_stage_trainable: false
    use_scheduler: true 
    scheduler_config:
      target: torch.optim.lr_scheduler.LinearLR
      params:
        start_factor: 1
        end_factor: 1e-3
        total_iters: 500
    use_automatic_optimization: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 20
        out_channels: 20
        model_channels: 128
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt
    cond_stage_config: 
      target: torch.nn.Identity

    test_only_params:
      # whether use legacy
      use_legacy: false 
      parameterization: kl 
      ckpt_path: $path
      # make dataset
      save_dataset: true 
      save_dataset_path: $path
      include_keys: [inputs, samples]
      suffix_keys: 
        inputs: .nii.gz
        samples: .nii.gz

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.base.DummyDataset
      params:
        split: train
        patch_size: [128, 128, 128]
    validation:
      target: ldm.data.base.DummyDataset
      params:
        split: val
        resize_to: [128, 128, 128]
        patch_size: 5
    test:
      target: ldm.data.base.DummyDataset
      params:
        split: test
        patch_size: [128, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          inputs: 
            target: mask_rescale
            params:
              n_mask: 20
          samples:
            target: mask_rescale
            params: 
              n_mask: 20

  trainer:
    benchmark: true
    limit_test_batches: 500