name: ldm
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - python=3.11.0=h7a1cb2a_3
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.0
      - acvl-utils==0.2
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alpha-transform==0.0.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - argparse==1.4.0
      - astra-toolbox==2.3.1.post0
      - astropy==7.1.0
      - astropy-iers-data==0.2025.5.26.0.37.21
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.2.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - batchgenerators==0.25
      - beautifulsoup4==4.12.3
      - blessed==1.20.0
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - connected-components-3d==3.17.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.1.1
      - datasets==3.6.0
      - decorator==5.1.1
      - deprecated==1.2.14
      - dicom2nifti==2.4.11
      - dill==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - einops-exts==0.0.4
      - elasticdeform==0.5.1
      - et-xmlfile==1.1.0
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - formulaic==1.0.2
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - future==1.0.0
      - gast==0.5.4
      - gdown==5.2.0
      - git-lfs==1.6
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - grpcio==1.63.0
      - h5py==3.11.0
      - healpy==1.18.1
      - hf-xet==1.1.3
      - huggingface-hub==0.33.0
      - humanize==4.9.0
      - idna==3.4
      - ignite==1.1.0
      - imageio==2.34.1
      - imgaug==0.4.0
      - interface-meta==1.3.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - kaleido==0.2.1
      - keras==3.3.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - lifelines==0.29.0
      - lightning-utilities==0.11.2
      - linecache2==1.0.0
      - lpips==0.1.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - medpy==0.5.1
      - ml-dtypes==0.3.2
      - monai==1.3.0
      - monai-generative==0.2.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - namex==0.0.8
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nibabel==5.2.1
      - numexpr==2.10.2
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.550.52
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optree==0.11.0
      - p-tqdm==1.4.0
      - packaging==24.0
      - pandas==2.2.2
      - pathos==0.3.2
      - pillow==10.2.0
      - pip==25.1.1
      - platformdirs==4.2.1
      - plotly==5.22.0
      - plyfile==1.1.2
      - pooch==1.8.2
      - pox==0.3.4
      - ppft==1.7.6.8
      - pretty-errors==1.2.25
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==20.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydeprecate==0.3.2
      - pydicom==2.4.4
      - pyerfa==2.0.1.5
      - pyfftw==0.15.0
      - pygments==2.18.0
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - python-papi==6.0.0.2
      - pytorch-fid==0.3.0
      - pytorch-lightning==1.8.4
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - radiomics==0.1
      - regex==2024.5.10
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.7.0
      - rotary-embedding-torch==0.8.5
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - scikit-video==1.1.11
      - scipy==1.13.0
      - scooby==0.11.0
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - setuptools==80.9.0
      - shapely==2.0.6
      - sharedmem==0.3.8
      - shellingham==1.5.4
      - silence-tensorflow==1.2.3
      - simpleitk==2.3.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sympy==1.12
      - tabulate==0.9.0
      - taming-transformers==0.0.1
      - tciaclient==0.0.3
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.16.1
      - tensorflow-estimator==2.15.0
      - tensorflow-gan==2.1.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-probability==0.24.0
      - termcolor==2.4.0
      - tf-keras==2.16.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2024.5.3
      - timm==0.9.16
      - tokenizers==0.19.1
      - torch==2.1.0+cu121
      - torch-fidelity==0.3.0
      - torch-radon==1.0.0
      - torchaudio==2.1.0+cu121
      - torchio==0.19.6
      - torchmetrics==0.11.4
      - torchvision==0.16.0+cu121
      - tqdm==4.66.4
      - traceback2==1.4.0
      - transformers==4.40.2
      - triton==2.1.0
      - typer==0.12.3
      - typing-extensions==4.15.0
      - tzdata==2024.1
      - unittest2==1.1.0
      - urllib3==1.26.13
      - vtk==9.5.2
      - wandb==0.17.0
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - werkzeug==3.0.3
      - wget==3.2
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.9.4
      - zenodo-get==1.6.1
      - zipp==3.19.2
