model:
  base_learning_rate: 2e-5
  train_target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/reconstruction_loss
    image_key: image
    embed_dim: 4
    # n_embed: 8192
    dims: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 20001
        disc_weight: 0.5
        gan_feat_weight: 1.
        n_frames_to_select: 3  # 1 as in medicaldiffusion

    ddconfig:
      double_z: false
      z_channels: 4
      resolution: [128, 128, 128]
      in_channels: 1
      out_ch: 1
      ch: 96
      ch_mult: [ 1, 2, 4 ]  
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      attn_type: none

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.base.SimpleDataset
      params:
        split: train
        patch_size: [128, 128, 128]
        use_aug: true
        any_dict: 
          image: /ailab/user/xxx/data/cttr.list
    validation:
      target: ldm.data.base.SimpleDataset
      params:
        split: val
        patch_size: [128, 128, 128]
        any_dict: 
          image: /ailab/user/xxx/data/ctval.list

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          inputs: 
            target: image_rescale
          reconstructions:
            target: image_rescale

  trainer:
    benchmark: true
    accumulate_grad_batches: 1
    limit_test_batches: 100