model:
  base_learning_rate: 2.e-5
  train_target: ldm.models.diffusion.ddpm.LatentDiffusion
  test_target: inference.models.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image_latents
    cond_stage_key: 
      concat: cond
      crossattn: prompt_context
    conditioning_key: hybrid
    image_size: [32, 128, 128]  # after first-stage encoding, infer size
    channels: 4               # after first-stage encoding
    monitor: train/loss_simple_ema_epoch
    cond_stage_trainable: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 6
        out_channels: 4
        model_channels: 64
        attention_resolutions: [8, 16]
        num_res_blocks: 2
        channel_mult: [1, 1, 2, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt
        use_spatial_transformer: true
        context_dim: 768

    logging_decoder:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/reconstruction_loss
        image_key: image
        embed_dim: 4
        # n_embed: 8192
        dims: 3
        lossconfig:
          target: torch.nn.Identity
        ckpt_path: /ailab/user/dailinrui-hdd/data/ldm/aekl_128_512_512/checkpoints/last.ckpt

        ddconfig:
          double_z: false
          z_channels: 4
          resolution: [128, 512, 512]
          in_channels: 1
          out_ch: 1
          ch: 4
          ch_mult: [ 1, 1, 2 ]  
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
          attn_type: none

    first_stage_config:
      target: ldm.modules.encoders.modules.IdentityFirstStage

    cond_stage_config: 
      target: torch.nn.Identity

  test_only_params:
    ckpt_path: $path
    save_dataset: true 
    save_dataset_path: $path
    suffix_keys: 
      samples: .nii.gz
      mask: .nii.gz

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 16
    wrap: False
    train:
      target: ldm.data.guidegen.GatheredEnsembleDatasetForLatentGeneration
      params:
        split: train
    validation:
      target: ldm.data.guidegen.GatheredEnsembleDatasetForLatentGeneration
      params:
        split: val
        max_size: 10
    test:
      target: ldm.data.guidegen.GatheredEnsembleDatasetForLatentGeneration
      params:
        split: test

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          samples:
            target: image_rescale

  trainer:
    benchmark: true
    max_epochs: 1000
    replace_sampler_ddp: true
    limit_test_batches: 500