model:
  base_learning_rate: 1.e-5
  train_target: ldm.models.diffusion.ddpm.LatentDiffusion
  test_target: inference.models.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    # first_stage_key: image
    first_stage_key: selected_projection
    cond_stage_key: selected_angle_in_degrees
    conditioning_key: crossattn
    image_size: [256, 256]  # after first-stage encoding, infer size
    channels: 1               # after first-stage encoding
    monitor: train/loss_simple
    cond_stage_trainable: true
    # use_ema: true
    # ckpt_path: /home/dlr/data/ldm/proj_256_256_test2/checkpoints/last.ckpt  

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 1
        out_channels: 1
        model_channels: 32
        attention_resolutions: [8]
        num_res_blocks: 1
        channel_mult: [1, 1, 1, 1]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt
        dims: 2
        use_spatial_transformer: true
        context_dim: 64

    first_stage_config:
      target: ldm.modules.encoders.modules.IdentityFirstStage

    cond_stage_config:
      target: ldm.modules.encoders.modules.AngleEmbedder
      params:
        embed_angles: [0, 90, 180, 270]
        d_embed: 64

  test_only_params:
    ckpt_path: $path
    save_dataset: true 
    save_dataset_path: $path
    suffix_keys: 
      samples: .nii.gz
      mask: .nii.gz
          
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: False
    common:
      target: ldm.data.synthetic.SVCTDatasetRepeat
      params:
        n_points: 0
        n_angles_total: 850 
        input_projection_min_max: [0, 1]
        input_volume_min_max: [0, 2]
        data_dir: /mnt/data_1/dlr/data/datasets/synthetic/projs_set0825_todai
    train:
      params:
        repeat: 200
        split: train
        n_angles: 64
        fixed_angle_per_case: false
    validation:
      params:
        split: val
        max_size: 6
        n_angles: 32
        fixed_angle_per_case: false

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          samples:
            target: image_rescale
          inputs:
            target: image_rescale
          reconstructions:
            target: image_rescale

  trainer:
    benchmark: true
    max_epochs: 1000
    replace_sampler_ddp: true
    limit_test_batches: 500